### ISSUE TITLE
Test not working?

### ISSUE THREAD

**Issue by cmdcolin** [akefirad/test-yargs-jest#1]
Hi there
Just stumbled on this repo via google search
I am having a heck of a time trying to find simplicity in the node js cli world and thought yargs might be good but i need tests to work

I ran this repo but i couldn't get tests to pass

it also seemed to only test the parser and not running any command/subcommand but that is maybe more of a minor issue

```
 ❯❯❯ git clone https://github.com/akefirad/test-yargs-jest                                                                                                                                         

...

 ❯❯❯ cd test-yargs-jest                    
 ❯❯❯ npm i

...

 ❯❯❯ npm run test

> yargs-jest@0.0.1 test
> jest

 FAIL  src/parsers.test.ts
  remote
    ✕ add (19 ms)

  ● remote › add

    expect(received).toEqual(expected) // deep equality

    Expected: "foo"
    Received: undefined

      16 |       },
      17 |     );
    > 18 |     expect(argv.name).toEqual("foo");
         |                       ^
      19 |     expect(argv.url).toEqual("bar");
      20 |   });
      21 | });

      at Object.<anonymous> (src/parsers.test.ts:18:23)

  console.log
    {"_":["remote","add","foo","bar"],"$0":"node_modules/.bin/jest"}

      at src/parsers.test.ts:9:17

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        0.749 s
Ran all test suites.

```

**Comment by akefirad** [comment]
You can’t get the tests to work because that’s exactly the purpose of this repo; to reproduce the issue 🙂
See [this](https://github.com/yargs/yargs/issues/1930) and [this](https://github.com/jestjs/jest/issues/11367).
(I also reached out to Jest team but no success 😕)

**Comment by cmdcolin** [comment]
ah didn't realize it was an error repro! i am just considering not running the cli in any realistic way, and just testing functions that yargs itself calls....much less satisfying of a test but oh well.
